// Core domain types for the Arabic verb system.
// Every verb is anchored on its present-tense "I" form (starts with أ),
// plus TWO memorized past anchors: past-of-انا and past-of-هو.
// From these, the whole grammar (6 tense structures) is generated by rule.

export type Family = 1 | 2 | 3 | 4 | 5;

export interface WordPair {
  ar: string; // Arabic script
  ph: string; // phonetic transliteration (7 = ح, 3 = ع, etc.)
}

export interface Verb {
  id: string;
  english: string; // "I see"
  arPresent: string; // أشوف  (present tense of "I")
  phPresent: string; // Ashuuf
  family: Family;
  pastAna: WordPair; // شفت / Shuft
  pastHuwa: WordPair; // شاف / Shaaf
  draft?: boolean; // true = AI-drafted, pending teacher verification
}

export interface VocabWord {
  id: string;
  english: string;
  ar: string;
  ph: string;
  category: string;
  draft?: boolean;
}

// Adjectives carry three spoken forms: masculine / feminine / plural (people).
export interface Adjective {
  id: string;
  english: string;
  masc: WordPair;
  fem: WordPair;
  plural: WordPair;
  draft?: boolean;
}

// Nouns carry singular + plural.
export interface Noun {
  id: string;
  english: string;
  singular: WordPair;
  plural: WordPair;
  category: string;
  draft?: boolean;
}

// The 8 spoken pronouns, split into the two "keys" of the system.
export type Pronoun =
  | 'ana'
  | 'inta'
  | 'inti'
  | 'intu'
  | 'ne7na'
  | 'huwe'
  | 'hiye'
  | 'humme';

export const PRONOUNS: { key: Pronoun; ar: string; en: string; group: 'ana' | 'huwe' }[] = [
  { key: 'ana', ar: 'أنا', en: 'I', group: 'ana' },
  { key: 'inta', ar: 'إنتَ', en: 'You (m)', group: 'ana' },
  { key: 'inti', ar: 'إنتِ', en: 'You (f)', group: 'ana' },
  { key: 'intu', ar: 'إنتو', en: 'You (pl)', group: 'ana' },
  { key: 'ne7na', ar: 'نحنا', en: 'We', group: 'ana' },
  { key: 'huwe', ar: 'هو', en: 'He', group: 'huwe' },
  { key: 'hiye', ar: 'هي', en: 'She', group: 'huwe' },
  { key: 'humme', ar: 'همة', en: 'They', group: 'huwe' },
];

export type ConjRow = { pronoun: Pronoun; ar: string; ph: string };
export type ConjTable = ConjRow[];

export interface VerbConjugation {
  pastDirect: ConjTable; // I wrote
  pastHabitual: ConjTable; // I used to write / I was writing (كان + present)
  presentSimple: ConjTable; // I write (with "be" ب)
  presentContinuous: ConjTable; // I am writing (عم + present)
  future: ConjTable; // I will write (راح + present, no "be")
  imperative: ConjRow[]; // only inta / inti / intu
}
